<a href="https://colab.research.google.com/github/gjuliao/Numpy_01/blob/main/Numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# 1. import numpy
import numpy as np

In [9]:
# 2. getting version of numpy
np.version.version

'1.26.4'

In [10]:
# 3. creating an array of zeros with length 10
y = np.zeros(10)
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
# 4. getting information of numpy add function
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [20]:
# 5. find memory size of an array
z = y.itemsize * y.size
print(z)

80


In [21]:
# 6. Create a null vector of size 10 but the fifth value which is 1
null_vector = np.zeros(10)
print(null_vector)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [22]:
# 7. vector from 10 to 50
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [25]:
# 8.  reverse vector
reverse_vector = vector[::-1]
print(reverse_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [29]:
# 9. vector with every 2 starting from index 0
other_vector = vector[::2]
print(other_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [30]:
# 10. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(0, 9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [47]:
# 10.1 creating an array
matrix2 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(matrix2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [55]:
# 10.3 creating an array with a reshape of 4x3
array2_increasing = np.arange(12).reshape(4, 3)
print(random_array2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [71]:
# 10.4 creating a random array of 5 elements under variable a, other one of b and multiplying it
a = np.random.randint(1, 10, size=5)
print('This is array a: ', a)
b = np.random.randint(2, 5, size=5)
print('This is array b: ', b)
c = np.dot(a, b)
print('This is the dot product of a and b: ', c)

This is array a:  [9 9 6 8 5]
This is array b:  [3 3 4 4 2]
This is the dot product of a and b:  120


In [61]:
# 10.4 creating an array of random values between 1 and 15 of length 11
random_array2 = np.random.randint(1, 15, size=11)
print(random_array2)

[14 10  8  2 12  7  2  1  1  5 12]


In [34]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
indices = np.nonzero([1, 2, 0, 0, 4, 0])
print(indices)

(array([0, 1, 4]),)


In [35]:
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
# Create a 3x3x3 array with random values
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.85721293 0.39873629 0.33705503]
  [0.56550736 0.4261887  0.53991488]
  [0.98586801 0.28209295 0.83033892]]

 [[0.32203193 0.07297393 0.03637563]
  [0.78344748 0.99127273 0.40358103]
  [0.11411924 0.41985618 0.69619068]]

 [[0.21211309 0.16752791 0.78593411]
  [0.17285561 0.68467852 0.994883  ]
  [0.56738848 0.15137026 0.61491462]]]


In [45]:
# function to create 4 arrays of 3x4
random_array2 = np.random.random((4, 3, 4))
print(random_array2)

[[[0.60995023 0.07543936 0.35653106 0.86449397]
  [0.31185422 0.88891524 0.16178221 0.32837217]
  [0.43922269 0.99571417 0.63598489 0.77178999]]

 [[0.23609068 0.29114618 0.1157541  0.32714416]
  [0.31128653 0.88874348 0.28471405 0.74108067]
  [0.83062066 0.63427948 0.47359187 0.2196655 ]]

 [[0.151592   0.65910557 0.91944361 0.66673453]
  [0.56744315 0.82833453 0.02438754 0.87284697]
  [0.11619677 0.53106228 0.79404656 0.42279732]]

 [[0.63470065 0.26495341 0.76887886 0.95436413]
  [0.93182499 0.99369972 0.76564787 0.9068713 ]
  [0.30727    0.72401054 0.18517509 0.87449945]]]
