<a href="https://colab.research.google.com/github/gjuliao/Numpy_01/blob/main/Numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# 1. import numpy
import numpy as np

In [9]:
# 2. getting version of numpy
np.version.version

'1.26.4'

In [10]:
# 3. creating an array of zeros with length 10
y = np.zeros(10)
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
# 4. getting information of numpy add function
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [20]:
# 5. find memory size of an array
z = y.itemsize * y.size
print(z)

80


In [21]:
# 6. Create a null vector of size 10 but the fifth value which is 1
null_vector = np.zeros(10)
print(null_vector)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [22]:
# 7. vector from 10 to 50
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [25]:
# 8.  reverse vector
reverse_vector = vector[::-1]
print(reverse_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [29]:
# 9. vector with every 2 starting from index 0
other_vector = vector[::2]
print(other_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [30]:
# 10. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(0, 9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [47]:
# 10.1 creating an array
matrix2 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(matrix2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [55]:
# 10.3 creating an array with a reshape of 4x3
array2_increasing = np.arange(12).reshape(4, 3)
print(random_array2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [71]:
# 10.4 creating a random array of 5 elements under variable a, other one of b and multiplying it
a = np.random.randint(1, 10, size=5)
print('This is array a: ', a)
b = np.random.randint(2, 5, size=5)
print('This is array b: ', b)
c = np.dot(a, b)
print('This is the dot product of a and b: ', c)

This is array a:  [9 9 6 8 5]
This is array b:  [3 3 4 4 2]
This is the dot product of a and b:  120


In [61]:
# 10.4 creating an array of random values between 1 and 15 of length 11
random_array2 = np.random.randint(1, 15, size=11)
print(random_array2)

[14 10  8  2 12  7  2  1  1  5 12]


In [34]:
# 11. Find indices of non-zero elements from [1,2,0,0,4,0]
indices = np.nonzero([1, 2, 0, 0, 4, 0])
print(indices)

(array([0, 1, 4]),)


In [35]:
# 13.  Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [75]:
# 14. Create a 4x2x3 array with random values
random_array = np.random.random((4, 2, 3))
print(random_array)

[[[0.87080476 0.89751435 0.20607401]
  [0.02157675 0.70978892 0.60788939]]

 [[0.99852191 0.94398093 0.7876507 ]
  [0.98287005 0.42051072 0.74401624]]

 [[0.84071477 0.36101527 0.79868338]
  [0.06399812 0.69797829 0.70639617]]

 [[0.91493087 0.54676652 0.4295209 ]
  [0.48745566 0.29244422 0.90514005]]]


In [45]:
# 15. function to create 4 arrays of 3x4
random_array2 = np.random.random((4, 3, 4))
print(random_array2)

[[[0.60995023 0.07543936 0.35653106 0.86449397]
  [0.31185422 0.88891524 0.16178221 0.32837217]
  [0.43922269 0.99571417 0.63598489 0.77178999]]

 [[0.23609068 0.29114618 0.1157541  0.32714416]
  [0.31128653 0.88874348 0.28471405 0.74108067]
  [0.83062066 0.63427948 0.47359187 0.2196655 ]]

 [[0.151592   0.65910557 0.91944361 0.66673453]
  [0.56744315 0.82833453 0.02438754 0.87284697]
  [0.11619677 0.53106228 0.79404656 0.42279732]]

 [[0.63470065 0.26495341 0.76887886 0.95436413]
  [0.93182499 0.99369972 0.76564787 0.9068713 ]
  [0.30727    0.72401054 0.18517509 0.87449945]]]


In [80]:
# 16. Create a 10x10 array with random values and find the minimum and maximum values
array_tenby_ten = np.random.random((10, 10))
min_value = np.min(array_tenby_ten)
max_value = np.max(array_tenby_ten)
print("Minimum value:", min_value)
print("Maximum value:", max_value)
print(array_tenby_ten)

Minimum value: 0.012027094633727309
Maximum value: 0.9963269450247525
[[0.51345564 0.89236412 0.98872454 0.17560874 0.72224662 0.07226514
  0.70268366 0.85733473 0.70250487 0.35158368]
 [0.15153197 0.79965417 0.65861372 0.29115862 0.39416275 0.0743402
  0.57770031 0.70076097 0.80158282 0.82379759]
 [0.6428184  0.42514348 0.92094345 0.98048648 0.66446056 0.98054392
  0.88982364 0.27828978 0.22720067 0.54367803]
 [0.99632695 0.68875149 0.82846287 0.11888916 0.98370701 0.95544748
  0.98941263 0.2571703  0.55169813 0.6468695 ]
 [0.01227314 0.43560608 0.07761872 0.13744363 0.39858248 0.67322932
  0.85806645 0.40571807 0.22235913 0.87202259]
 [0.23052946 0.51177437 0.02481844 0.11051648 0.19966777 0.65444841
  0.48291281 0.11383816 0.49472658 0.08173235]
 [0.64497473 0.6289236  0.19360122 0.86039231 0.3631201  0.65779002
  0.43855978 0.32116261 0.32644414 0.79691119]
 [0.02215482 0.2501004  0.09205262 0.65459865 0.054402   0.34817606
  0.19065672 0.87322972 0.78072017 0.82202256]
 [0.0901005

In [82]:
# 17. Random vector of size 30 and find mean value
random_vector = np.random.random(30)
print(random_vector)
mean_value = np.mean(random_vector)
print("Mean value:", mean_value)

[0.61513886 0.13506845 0.6506666  0.17927634 0.1436265  0.65099767
 0.7340116  0.88844524 0.62898874 0.03704128 0.79755296 0.40676852
 0.705104   0.07572191 0.91324944 0.65246105 0.79626503 0.98530983
 0.72269804 0.02027743 0.23014818 0.78312773 0.40419278 0.46144979
 0.72015239 0.37821122 0.09734305 0.76303004 0.67830133 0.25028524]
Mean value: 0.5168303733800536


In [84]:
# 18. Create a 2d array with 1 on the border and 0 inside
array_2d = np.ones((6, 6))
array_2d[1:-1, 1:-1] = 0
print(array_2d)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [85]:
# 18.1
zero_borders = np.zeros((6, 6))
zero_borders[1:-1, 1:-1] = 1
print(zero_borders)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [86]:
0 * np.nan

nan

In [87]:
np.nan == np.nan

False

In [92]:
np.inf > np.nan

False

In [93]:
np.nan - np.nan

nan

In [94]:
np.nan in set([np.nan])

True

In [95]:
0.3 == 3 * 0.1

False

In [96]:
# 19 what is the ending value
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [97]:
# 20.  Printing the eye
matrix = np.eye(5, 5)
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [98]:
# 21. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
matrix = np.diag(1+np.arange(4), k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [102]:
# 22.  Create a 8x8 matrix and fill it with a checkerboard pattern

eight_by_eight = np.zeros((8, 8), dtype=int)
eight_by_eight[1::2, ::2] = 1
eight_by_eight[::2, 1::2] = 1
print(eight_by_eight)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [117]:
# 23. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
array = np.unravel_index(100, (6, 7, 8))
print(array)

(14, 2)


In [122]:
# 24. Create a checkerboard 8x8 matrix using the tile function
checkerboard = np.array([[0, 1], [1, 0]])
checkerboard_matrix = np.tile(checkerboard, (8, 8))
print(checkerboard_matrix)

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]


In [123]:
# 25 Normalize a 5x5 random matrix
random_matrix = np.random.random((5, 5))
normalized_matrix = (random_matrix - np.mean(random_matrix)) / np.std(random_matrix)
print(normalized_matrix)

[[-1.3986773  -1.28261938  1.22112424  0.72572494  1.0195727 ]
 [-0.60322693  0.31436002  0.92222187  0.98976125  1.61680904]
 [ 1.32451969  1.13766423  0.17078086  0.22940586  0.00575242]
 [ 0.12644154 -0.61419492  0.09413572 -1.17549048 -0.73113231]
 [-0.98244419 -0.93792236 -1.58644094 -1.60683714  1.02071157]]


In [124]:
# 26. Create a custom dtype that describes a color as four unsigned bytes
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-124-e3c9800a7da0>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [130]:
# 26. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

a = np.random.random((5, 3))
print('this is a:', a)
b = np.random.random((3, 2))
print('this is b:', b)
c = np.dot(a, b)
print('this is a x b:', c)

this is a: [[0.26653075 0.09420055 0.99021657]
 [0.34433938 0.98172857 0.62404378]
 [0.32440118 0.6398265  0.56010689]
 [0.90886872 0.19424812 0.7686626 ]
 [0.2058996  0.47973713 0.72750595]]
this is b: [[0.0503079  0.35387324]
 [0.49607293 0.59298134]
 [0.93033536 0.59298701]]
this is a x b: [[0.98137244 0.73736284]
 [1.08490195 1.07404908]
 [0.8548078  0.82633819]
 [0.85719851 0.89261677]
 [0.92516749 0.78873911]]


In [131]:
# 26. Given a 1D array, negate all elements which are between 3 and 8, in place.
array = np.arange(11)
print(array)
array[(3 < array) & (array < 8)] *= -1
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
